---
# ------------------------------------------------------------------------------------------------------------------
# Playbook: /roles/win-domaincontroller
# Purpose: Add additional domain controllers to a child domain or forest
#
# Inputs: win_topology	- Forest topology parameters
#		  win_site		- Site specific parameters
#		  win_adports	- List of TCP and UDP ports to validate
# 		  
# This playbook will perform the following tasks:
# - Check that required ports are opened on firewall (and Nova security groups)
# - Configure host DNS client settings to allow the new domain controller to locate primary DCPROMO
# - Condigure AD Sites and Site Links for the current given site
# - Configure any additional site-specific OUs
# - Execute "dcpromo"
# - Restart the host
# ------------------------------------------------------------------------------------------------------------------

# Set DNS client servers so we can find the domain controller
- name: ConfigureTCPIP
  script: files/configureNetworking.ps1 -Placement "{{ win_domainplacement }}" -Topology "{{ win_topology | dictToPS }}" -UseParentDNS

# Check if all ports to the first forest domain controller are open
- name: CheckPorts
  script: files/checkPorts.ps1 -TargetSystem "{{ win_topology.forest.primaryDNS }}" -TestPorts "{{ win_adports | dictToPS }}"

# Set the delegation server
- include: "{{playbook_dir}}/includes/win-setparentdelegate.yml"

# Prepare the Site and Site Links for the given site
- name: PrepareSiteAndLinks
  script: files/configureSitesAndLinks.ps1 -Topology "{{ win_topology | dictToPS }}" -Site "{{ win_site | dictToPS }}"  
  delegate_to: "{{ win_delegate }}"
  connection: winrm
  remote_user: "{{ ansible_ssh_user }}"
  run_once: true

# Prepare the site-specific OUs
- name: PrepareSiteSpecificOUs
  script: files/configureSiteOUs.ps1 -SiteName "{{ win_site.sitename }}" -DomainOUs "{{ win_ous | dictToPS }}"
  delegate_to: "{{ win_delegate }}"
  connection: winrm
  remote_user: "{{ ansible_ssh_user }}"
  run_once: true

# Install ADDS role and features
- name: InstallADDS
  script: files/installADDS.ps1

# Install AD components and create the forest
- name: PromoteDomainController
  script: promoteDomainController.ps1 -Placement "{{ win_domainplacement }}" -Topology "{{ win_topology | dictToPS }}" -Site "{{ win_site | dictToPS }}"

# Configure DNS client settings using reversed primary and secondary
- name: ConfigureTCPIP
  script: files/configureNetworking.ps1 -Placement "{{ win_domainplacement }}" -Topology "{{ win_topology | dictToPS }}" -ReverseDNS

# Restart
- include: "{{playbook_dir}}/includes/win-restart.yml"
